config/routes.rb
Rails.application.routes.draw do

  get 'users/profile' 
  get 'users/profile', as: 'user_root'
  get 'landings/index'
  
  devise_for :users
  
  resources :hotels do
    resources :raitings, only: :create
  end

  root 'landings#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  belongs_to :user
  has_one :address
  has_many :raitings

  accepts_nested_attributes_for :address

  mount_uploader :foto, FotoUploader

  validates :title, presence: true, length: {minimum: 5}
  validates :stars, presence: true

=begin
  def top_five
    hotels = []
    all.each do |hotel|
      hotel.raitings.average(:raiting)
    end
  end
=end

  def update_raiting
    aver = Raiting.average('raiting')
    update(aver_raiting: aver)
  end

end

app/models/raiting.rb
class Raiting < ActiveRecord::Base
  belongs_to :hotel
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hotels
  has_many :raitings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

  def new
    @hotel = Hotel.new
    @hotel.address = Address.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    @hotel.user = current_user
    @hotel.save ? redirect_to(@hotel) : render("hotels/new")
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    redirect_to hotels_path
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :stars, :rooms, :price, :breakfast, :foto, :foto_cache,
                                  address_attributes: [:country, :state, :city, :street])
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    #@top_5 = Hotel.top_five
  end
end

app/controllers/raitings_controller.rb
class RaitingsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @hotel = Hotel.find(params[:hotel_id])
    @raiting = @hotel.raitings.build(raiting_params)
    @raiting.user = current_user
    @raiting.save
    @hotel.update_raiting
    redirect_to hotel_path(@hotel)
  end



  private

  def raiting_params
    params.require(:raiting).permit(:commenter, :comment, :raiting)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/raitings_helper.rb
module RaitingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
      <tr class="danger">
        <th class="col-md-1">Show</th>
        <th class="col-md-2">Title</th>
        <th class="col-md-2">Raitings</th>
        <th class="col-md-2">Aver_raiting</th>
        <th class="col-md-3">Description</th>
        <th class="col-md-3">Address</th>
        <th class="col-md-2">Foto</th>
        <th class="col-md-1">Delete!</th>
      </tr>
      </thead>

      <% @hotels.each do |hotel| %>
        <tbody>
        <tr>
          <td><%= link_to 'Show', hotel_path(hotel.id) %></td>
          <td><b><%= hotel.title %></b><span> stars: </span><%= hotel.stars %></td>
          <td>
            <% hotel.raitings.each do |r| %>
              <p><%= r.raiting %></p>
            <% end %>
          </td>
          <td><%= hotel.aver_raiting %></td>
          <td>
            <p><%= hotel.rooms %></p>
            <p>Price: <%= hotel.price %></p>
            <p>Breakfast:
              <% if hotel.breakfast %>
                <b>present</b>
              <% else %>
                <b>no breakfast</b>
              <% end %>
            </p>
          </td>
          <td>
            <ul class="list-unstyled">
              <li>Country: <%= hotel.address.country %></li>
              <li>State: <%= hotel.address.state %></li>
              <li>City: <%= hotel.address.city %></li>
              <li>Street: <%= hotel.address.street %></li>
            </ul>
          </td>
          <td>
            <%= image_tag hotel.foto.url.to_s, height: '100px' if hotel.foto? %>
          </td>
          <td>
            <%= link_to 'X', hotel_path(hotel), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
        </tbody>
      <% end %>
    </table>

    <%= link_to 'Add Hotel', new_hotel_path %>
  </div>
</div> 

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<div class="col-md-6 col-md-offset-3">

  <% if @hotel.errors.any? %>
    <div id="error_explanation" class="well">
      <h2 class="panel-danger">
        <%= pluralize(@hotel.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul class="list-unstyled">
        <% @hotel.errors.full_messages.each do |msg| %>
          <li class="label-danger"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= simple_form_for @hotel do |f| %>
    <%= f.input :title, label: 'Hotel name' %>
    <%= f.input :stars, as: :radio_buttons, collection: 1..5, label: 'Number of stars' %>
    <%= f.input :rooms, :label => 'Hotel description' %>
    <%= f.input :price, :label => 'Price for room' %>
    <%= f.input :breakfast, as: :boolean, :label => 'Breakfast  included' %>
    <%= f.input :foto, :label => 'Upload foto' %>

    <h3>Address</h3>
    <%= f.simple_fields_for :address do |ad| %>
      <%= ad.input :country, as: :string, label: 'Country' %>
      <%= ad.input :state, label: 'State' %>
      <%= ad.input :city, label: 'City' %>
      <%= ad.input :street, label: 'Street' %>
    <% end %>

    <%= f.button :submit, :class => 'btn-danger' %>
  <% end %>

  <br/>
  <%= link_to 'To hotel list', hotels_path %>
</div>

app/views/hotels/show.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table table-hover">
      <thead>
      <tr class="danger">
        <th class="col-xs-1">Title</th>
        <th class="col-xs-6">Description</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td class="col-xs-1">Title:</td>
        <td class="col-xs-6"><%= @hotel.title %></td>
      </tr>
      <tr>
        <td class="col-xs-1">Stars:</td>
        <td class="col-xs-6"><%= @hotel.stars %></td>
      </tr>
      <tr>
        <td class="col-xs-1">Rooms:</td>
        <td class="col-xs-6"><%= @hotel.rooms %></td>
      </tr>
      <tr>
        <td class="col-xs-1">Price:</td>
        <td class="col-xs-6"><%= @hotel.price %></td>
      </tr>
      <tr>
        <td class="col-xs-1">Breakfast:</td>
        <% if @hotel.breakfast %>
          <td class="col-xs-6">present</td>
        <% else %>
          <td class="col-xs-6">no breakfast</td>
        <% end %>
      </tr>
      <tr>
        <td class="col-xs-1">Foto:</td>
        <td class="col-xs-6"><%= image_tag @hotel.foto.url.to_s, height: '100px' if @hotel.foto? %>
        </td>
      </tr>
      <tr>
        <td>Address</td>
        <td class="col-xs-6">
          <ul class="list-unstyled">
            <li>Country: <%= @hotel.address.country %></li>
            <li>State: <%= @hotel.address.state %></li>
            <li>City: <%= @hotel.address.city %></li>
            <li>Street: <%= @hotel.address.street %></li>
          </ul>
        </td>
      </tr>
      </tbody>
    </table>
    <br>

    <h2>Comments</h2>

      <% @hotel.raitings.each do |raiting| %>
        <div class="well">
          <p>
            <strong>Commenter:</strong>
            <%= raiting.commenter %>
          </p>
          <p>
            <strong>Comment:</strong>
            <%= raiting.comment %>
          </p>
          <p>
            <strong>Raiting:</strong>
            <%= raiting.raiting %>
          </p>
        </div>
      <% end %>


    <h2>Add a comment:</h2>
      <%= simple_form_for([@hotel, @hotel.raitings.build]) do |f| %>
        <p>
          <%= f.label :commenter %><br>
          <%= f.text_field :commenter %>
        </p>

        <p>
          <%= f.label :comment %><br>
          <%= f.text_area :comment %>
        </p>

        <p>
          <%= f.input :raiting, as: :radio_buttons, collection: 1..5 %>
        </p>

        <p>
          <%= f.submit %>
        </p>
      <% end %>

    <p><%= link_to 'Add Hotel', new_hotel_path %></p>

    <p><%= link_to 'Back to hotel list', hotels_path %></p>
  </div>
</div>

app/views/landings/index.html.haml
.center.jumbotron
  %h1
    Welcome to Hotelius!
    %br
    %small
      The best hotel raiting site

  = link_to "Sign up now!", new_user_registration_path, class: "btn btn-danger btn-lg"
%h3
  This is the list of TOP 5 hotels

%h4
  = link_to 'Sign in ', new_user_session_path
  to#{link_to ' add new hotel', new_hotel_path}

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The RoR based simple hotel advisor aplication.
  </small>
  <nav>
    <ul class="list-unstyled list-inline nav navbar-nav pull-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Hotels", hotels_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "", root_path, id: "logo" %>
      <nav>
        <ul class="list-unstyled list-inline nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Hotels", hotels_path %></li>
          <% if user_signed_in? %>
            <li>
              <span>Hello, <%= current_user.email %></span>
            </li>
            <li><%= link_to 'Sign out', destroy_user_session_path, class: 'sign_out', :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><span>or</span></li>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
          <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hotelius</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">

  <%= yield %>

</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/users/profile.html.haml
%h1 Users#profile
%p Find me in app/views/users/profile.html.haml